// <auto-generated />
using System;
using CarConsoleApplication.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CarConsoleApplication.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260215112750_AddSettingsTables")]
    partial class AddSettingsTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CarConsoleApplication.Entities.ClimateSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<short>("FanSpeed")
                        .HasColumnType("smallint");

                    b.Property<int>("TargetTemperatureC")
                        .HasColumnType("integer");

                    b.Property<bool>("ZoneDriver")
                        .HasColumnType("boolean");

                    b.Property<bool>("ZonePassenger")
                        .HasColumnType("boolean");

                    b.Property<bool>("ZoneRear")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("ClimateSettings");
                });

            modelBuilder.Entity("CarConsoleApplication.Entities.DisplaySettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AutoBrightness")
                        .HasColumnType("boolean");

                    b.Property<int>("Brightness")
                        .HasColumnType("integer");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ReduceMotion")
                        .HasColumnType("boolean");

                    b.Property<int>("ScreenTimeoutSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("TextSize")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Units")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DisplaySettings");
                });

            modelBuilder.Entity("CarConsoleApplication.Entities.DrivingSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("CollisionWarningEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("CruiseDefaultKmh")
                        .HasColumnType("integer");

                    b.Property<string>("DriveMode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LaneAssistEnabled")
                        .HasColumnType("boolean");

                    b.Property<short>("LaneAssistIntensity")
                        .HasColumnType("smallint");

                    b.Property<bool>("ParkingSensorsEnabled")
                        .HasColumnType("boolean");

                    b.Property<short>("RegenLevel")
                        .HasColumnType("smallint");

                    b.Property<bool>("TrafficSignRecognition")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("DrivingSettings");
                });

            modelBuilder.Entity("CarConsoleApplication.Entities.LightSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AutoHighBeam")
                        .HasColumnType("boolean");

                    b.Property<int>("Brightness")
                        .HasColumnType("integer");

                    b.Property<string>("HeadlightMode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("LightsSettings");
                });

            modelBuilder.Entity("CarConsoleApplication.Entities.SeatingSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<short>("DriverSeatPreset")
                        .HasColumnType("smallint");

                    b.Property<bool>("EasyEntry")
                        .HasColumnType("boolean");

                    b.Property<short>("PassengerSeatPreset")
                        .HasColumnType("smallint");

                    b.Property<short>("SeatHeatingDriverLevel")
                        .HasColumnType("smallint");

                    b.Property<short>("SeatHeatingPassengerLevel")
                        .HasColumnType("smallint");

                    b.Property<short>("SeatVentDriverLevel")
                        .HasColumnType("smallint");

                    b.Property<short>("SeatVentPassengerLevel")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("SeatingSettings");
                });

            modelBuilder.Entity("CarConsoleApplication.Entities.ServiceSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("LastServiceAtKm")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastServiceDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PreferredServiceCenter")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ServiceIntervalKm")
                        .HasColumnType("integer");

                    b.Property<int>("ServiceIntervalMonths")
                        .HasColumnType("integer");

                    b.Property<bool>("ServiceReminderEnabled")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("ServiceSettings");
                });

            modelBuilder.Entity("CarConsoleApplication.Entities.SoftwareSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AutoUpdate")
                        .HasColumnType("boolean");

                    b.Property<bool>("CrashReports")
                        .HasColumnType("boolean");

                    b.Property<bool>("DiagnosticsSharing")
                        .HasColumnType("boolean");

                    b.Property<bool>("ResetToDefaultsAllowed")
                        .HasColumnType("boolean");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UpdateChannel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Use24HourClock")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("SoftwareSettings");
                });

            modelBuilder.Entity("CarConsoleApplication.Entities.VehicleSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AutoLock")
                        .HasColumnType("boolean");

                    b.Property<bool>("AutoUnlockOnPark")
                        .HasColumnType("boolean");

                    b.Property<bool>("DoorLockSound")
                        .HasColumnType("boolean");

                    b.Property<bool>("MirrorFoldOnLock")
                        .HasColumnType("boolean");

                    b.Property<int>("SpeedLimitOffsetKmh")
                        .HasColumnType("integer");

                    b.Property<bool>("SpeedLimitWarningEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("TirePressureUnit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("WipersServicePosition")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("VehicleSettings");
                });

            modelBuilder.Entity("CarConsoleApplication.Models.ConsoleSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MapDefaultZoom")
                        .HasColumnType("integer");

                    b.Property<bool>("NotificationsEnabled")
                        .HasColumnType("boolean");

                    b.Property<double>("RouteEndLat")
                        .HasColumnType("double precision");

                    b.Property<double>("RouteEndLon")
                        .HasColumnType("double precision");

                    b.Property<int>("RouteRefreshSeconds")
                        .HasColumnType("integer");

                    b.Property<double>("RouteStartLat")
                        .HasColumnType("double precision");

                    b.Property<double>("RouteStartLon")
                        .HasColumnType("double precision");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Units")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("CarConsoleApplication.Models.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Location")
                        .HasColumnType("integer");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MenuItems");
                });

            modelBuilder.Entity("CarConsoleApplication.Models.RoutePoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Sequence");

                    b.ToTable("RoutePoints");
                });
#pragma warning restore 612, 618
        }
    }
}
